//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_Final.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PatientsDBEntities : DbContext
    {
        public PatientsDBEntities()
            : base("name=PatientsDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Complains> Complains { get; set; }
        public virtual DbSet<Diagnosis> Diagnosis { get; set; }
        public virtual DbSet<Diseases> Diseases { get; set; }
        public virtual DbSet<Examinations> Examinations { get; set; }
        public virtual DbSet<Findings> Findings { get; set; }
        public virtual DbSet<Informations> Informations { get; set; }
        public virtual DbSet<Inspections> Inspections { get; set; }
        public virtual DbSet<Medicines> Medicines { get; set; }
        public virtual DbSet<Patients> Patients { get; set; }
        public virtual DbSet<Photos> Photos { get; set; }
        public virtual DbSet<Surgeries> Surgeries { get; set; }
        public virtual DbSet<Treatment_Plans> Treatment_Plans { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
